controllers:

    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
map:
    path: /map
    controller: App\Controller\conn::index

admin_menu:
    path: /admin/menu
    controller: App\Controller\AdminController::admin